This code file is to expermiment with how to make a live to-do lis for the discord bot

Features: 

-- Update to-do list with new entry

-- Send regular reminders based on user preference

-- Adjust priority (easily)

-- Mark different stages and track completion

Things to add to To-Do List:


CODING PROJECTS:
- Code Learning Tracker
- Peronsal Health Tracker (workouts, sleep, etc)
- Financial Tracker
- General Video Game Tracker (100%, game-picker)

In [4]:
# Importing Libaries


import numpy as np
import pandas as pd

import datetime
import os

In [5]:
pd.DataFrame({'A': [1, 2, 3]})

   A
0  1
1  2
2  3

In [8]:
to_list_pd = pd.DataFrame(
    {
        "TASK": "string",
        "TASK CREATION": pd.to_datetime(datetime.datetime.now().isoformat(' ', 'seconds')),

        "CATAGORY": pd.Categorical(["None"]),
        "GROUP": "None",
        "SUB-GROUP": "None",

        "RELEVANT LINK": 'https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html', 

        "RECURRING": False,
        "RECURRING INTERVAL": [24],
        "DUE DATE": pd.to_datetime("20130102"),

        "PRIORITY": [10],
        "STATUS": pd.Categorical(["Not Started"], 
                                 categories = [
                                     "Not Started",
                                     "In Progress",
                                     "Pending",
                                     "Blocked",
                                     "Hiatus",
                                     "Completed"
                                               ], 
                                 ordered= True),
        "START TIME": pd.Timestamp("20130102"),
        "ESTIMATED TIME": [24],
        "LOGGED HOURS": [24],

        "COMPLETED": True,
        "COMPLETED TIME": pd.Timestamp("20130102")


    }
)

# pd.Categorical(["test", "train", "test", "train"]),
to_list_pd

,TASK,TASK CREATION,CATAGORY,GROUP,SUB-GROUP,RELEVANT LINK,RECURRING,RECURRING INTERVAL,DUE DATE,PRIORITY,STATUS,START TIME,ESTIMATED TIME,LOGGED HOURS,COMPLETED,COMPLETED TIME
0,string,2025-03-25 00:06:23,None,None,None,https://pandas.pydata.org/docs/reference/api/p...,False,24,2013-01-02,10,Not Started,2013-01-02,24,24,True,2013-01-02

In [9]:
to_list_pd.dtypes

TASK                          object
TASK CREATION         datetime64[ns]
CATAGORY                    category
GROUP                         object
SUB-GROUP                     object
RELEVANT LINK                 object
RECURRING                       bool
RECURRING INTERVAL             int64
DUE DATE              datetime64[ns]
PRIORITY                       int64
STATUS                      category
START TIME             datetime64[s]
ESTIMATED TIME                 int64
LOGGED HOURS                   int64
COMPLETED                       bool
COMPLETED TIME         datetime64[s]
dtype: object

In [11]:
test = pd.DataFrame(
    {
        "TASK": "Code Learning Tracker",
        "TASK CREATION": pd.Timestamp("20130102"),

        "CATAGORY": pd.Categorical(["None"]),
        "GROUP": "None",
        "SUB-GROUP": "None",
        "PRIMARY KEY": "None",

        "RELEVANT LINK": "None", 

        "RECURRING": True,
        "RECURRING INTERVAL": [24],
        "DUE DATE": pd.Timestamp("20130102"),

        "PRIORITY": [10],
        "STATUS": pd.Categorical(["test"], 
                                 categories = [
                                     "Not Started",
                                     "In Progress"
                                     "Pending"
                                     "Blocked"
                                     "Hiatus"
                                     "Completed"
                                               ], 
                                 ordered= True),
        "START TIME": pd.Timestamp("20130102"),
        "ESTIMATED TIME": [24],

        "COMPLETED": True,
        "COMPLETED TIME": pd.Timestamp("20130102")


    }
)

test

,TASK,TASK CREATION,CATAGORY,GROUP,SUB-GROUP,PRIMARY KEY,RELEVANT LINK,RECURRING,RECURRING INTERVAL,DUE DATE,PRIORITY,STATUS,START TIME,ESTIMATED TIME,COMPLETED,COMPLETED TIME
0,Code Learning Tracker,2013-01-02,None,None,None,None,None,True,24,2013-01-02,10,NaN,2013-01-02,24,True,2013-01-02

In [12]:
test2 = pd.concat([to_list_pd, test])

test2

C:\Users\Preston Robertson\AppData\Local\Temp\ipykernel_13908\4209181342.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  test2 = pd.concat([to_list_pd, test])

,TASK,TASK CREATION,CATAGORY,GROUP,SUB-GROUP,RELEVANT LINK,RECURRING,RECURRING INTERVAL,DUE DATE,PRIORITY,STATUS,START TIME,ESTIMATED TIME,LOGGED HOURS,COMPLETED,COMPLETED TIME,PRIMARY KEY
0,string,2025-03-25 00:06:23,None,None,None,https://pandas.pydata.org/docs/reference/api/p...,False,24,2013-01-02,10,Not Started,2013-01-02,24,24.0,True,2013-01-02,NaN
0,Code Learning Tracker,2013-01-02 00:00:00,None,None,None,None,True,24,2013-01-02,10,NaN,2013-01-02,24,NaN,True,2013-01-02,None

In [8]:
os.getcwd()

'd:\\GitLaptop\\Discord Bot\\LuigiBot\\to_do_list'

In [45]:
to_list_pd.to_pickle("to_do_list_test.pkl")

In [69]:
test2 = pd.read_pickle("to_do_list_test.pkl")
test2

,TASK,TASK CREATION,CATAGORY,GROUP,SUB-GROUP,RELEVANT LINK,RECURRING,RECURRING INTERVAL,DUE DATE,PRIORITY,STATUS,START TIME,ESTIMATED TIME,LOGGED HOURS,COMPLETED,COMPLETED TIME
0,string,2025-03-25 00:06:23,None,None,None,https://pandas.pydata.org/docs/reference/api/p...,False,24,2013-01-02,10,Not Started,2013-01-02,24,24,True,2013-01-02

In [74]:
print(test2.loc[:, ["TASK", "PRIORITY", "STATUS", "DUE DATE", "RELEVANT LINK"]].astype(str).to_markdown(index = False))


#Embed Links in discord with [embed name](https://embedlink)

| TASK   |   PRIORITY | STATUS      | DUE DATE   | RELEVANT LINK                                                                  |
|:-------|-----------:|:------------|:-----------|:-------------------------------------------------------------------------------|
| string |         10 | Not Started | 2013-01-02 | https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html |

In [ ]:
#!pip install tabulate
#!pip install markdownify

# import markdownify
# Does not work in this scenario


from IPython.display import HTML

html_test = test2.loc[:, ["TASK", "PRIORITY", "STATUS", "DUE DATE", "RELEVANT LINK"]].astype(str)

html_test['RELEVANT LINK']  = '<a href=' + html_test['RELEVANT LINK']  + '><div>'+ 'HERE' + '</div></a>'

html_test = html_test.to_html(render_links=True, escape=False)
HTML(html_test)





#print(test2.loc[:, ["TASK", "PRIORITY", "STATUS", "DUE DATE", "RELEVANT LINK"]].astype(str).to_markdown())

In [79]:




dis_link_t = test2.loc[:, ["TASK", "PRIORITY", "STATUS", "RELEVANT LINK"]].astype(str)

dis_link_t['RELEVANT LINK']  = '[HERE]('+ dis_link_t['RELEVANT LINK']+ ')'

print(dis_link_t.to_markdown(index=False))

| TASK   |   PRIORITY | STATUS      | RELEVANT LINK                                                                          |
|:-------|-----------:|:------------|:---------------------------------------------------------------------------------------|
| string |         10 | Not Started | [HERE](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html) |